config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#home'

  resource :cart, only: [:show] 
  resources :orders 

  resources :products, only: [:index, :show] do 
    member do 
      post :add_to_cart
    end
  end

  resource :profile
  resources :offers, only: :create do 
    member do
      patch 'offer', as: 'vote'
    end
  end

  namespace :admin do
    root 'admin#root'
    resources :users, except: [:new, :create]
    resources :products, except: :show
    resources :offers, except: :show
  end

  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'
  
end

app/models/user.rb
class User < ActiveRecord::Base
	extend Enumerize 
	enumerize :role, in: [:admin, :moderator, :user], default: :user
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	has_one :profile, dependent: :destroy
	has_many :carts, dependent: :destroy
	has_many :orders, dependent: :destroy
	has_one :profile, dependent: :destroy

	has_secure_password

	validates :password, length: { minimum: 6 }
	validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }

	after_create :create_cart_for_user
	before_create :create_remember_token
	before_save ->{ email.downcase! }

	def full_name
		profile.nil? ? email : profile.full_name
	end

	def select_active_cart
		carts.active.last
	end

	def active_cart=(cart)
		carts.active.each { |c| c.update_attribute(:status, false) }
		cart.update_attributes(user_id: id, status: true)
	end

	def superuser?
		self.role.moderator? || self.role.admin?
	end

    def self.most_active_user_for_period(count_day = 7)
    	relation = where("orders.created_at >= ?", Time.now - count_day.day).group('users.id').joins(:orders)
    	relation.having("count(*) = ?", relation.count.values.max)
    end

    def self.new_remember_token
    	SecureRandom.urlsafe_base64
    end

    def self.encrypt(token)
    	Digest::SHA1.hexdigest(token.to_s)
    end

  private 

	def create_cart_for_user
		Cart.create(user: self, cart_token: SecureRandom.urlsafe_base64)
	end

	def create_remember_token
		self.remember_token = User.encrypt(User.new_remember_token)
	end
	
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
	def index
		@users = User.all
	end

	def destroy
		@user.destroy
		redirect_to users_path, notice: "User deleted."
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user, only: [:edit, :update] ####ДИМАС, СДЕЛАЙ КРАСИВУЮ ДОМАШНЮЮ СТРАНИЦУ ТИПА COOL SHOP
	before_action except: [:new, :create] { @user = current_user }
	before_action only: [:new, :create] { redirect_back_or root_url if signed_in? }
	
	#before_action :correct_user, only: [:edit, :update]


	def new 
		@user = User.new
	end	

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			flash[:success] = "Welcome to Mega-shop!"
			redirect_back_or root_url
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:success] = "success update"
			redirect_to profile_path
		else
			flash[:error] = "error"
			redirect_to edit_user_path
		end
	end


	private
	
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/users/_error_messages.html.slim
- if @user.errors.any?
	.alert.alert-danger@alert
		strong Errors:
		ul
			- @user.errors.full_messages.each do |msg|
				li = msg

app/views/users/edit.html.erb
<%= form_for users_path do |f| %>
  <p>Имя</p>
  <p>Эектронная почта</p>
  <%= f.text_area :email %><br>
  <p>
    <%= f.label :role %>
    <%= f.select :role, User.role.options %>
  </p>
  <p>Пароль</p>
  <%= f.text_field :password %><br>
  <p>Повторите пароль</p>
  <%= f.text_field :password_confirmation %> <br>
  <%= f.submit "Обновить" %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |us| %>
	<p><%= link_to us.full_name, user_path(us.id) %></p><hr>
<% end %>
<%= link_to "sign up", sign_up_path %>

app/views/users/new.html.slim
.center-block
	h1 Создание пользователя
	= form_for @user, url: sign_up_path, html: { class: "form-horizontal" } do |f| 
		= render 'error_messages'
		.form-group
			= f.label :email, class: "col-sm-2 control-label"
			.col-sm-4
				= f.email_field :email, class: "form-control", placeholder: "Email"
		.form-group
			= f.label :password, class: "col-sm-2 control-label"
			.col-sm-4
				= f.password_field :password, class: "form-control", placeholder: "Password"
		.form-group
			= f.label :password_confirm, class: "col-sm-2 control-label"
			.col-sm-4
				= f.password_field :password_confirmation, class: "form-control", placeholder: "Password confirm"
		
		.form-group
			.col-sm-offset-2.col-sm-1
				= submit_tag "Sign up!", class: "btn btn-default"

app/views/users/replenish_balance.html.erb
<%= form_for @user, url: replenish_balance_user_path do |f| %>
  <p>Current balance: <%= @user.balance %></p>
  <p>Replenish: </p>

  <%= f.text_field :balance %><br>
  
  <%= f.submit "Replenish" %>

<% end %>

app/views/users/show.html.erb
<h3><%= @user.full_name %></h3>
<p><%= @user.email %> </p>
<%= link_to "Редактировать", edit_user_path %> 
<% if signed_in? && (current_user.role.admin? || current_user?(@user)) %>
	<%= link_to "Удалить", @user, :method => :delete %> 
<% end %>