config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#home'

  resource :cart, only: [:show] 
  resources :orders 

  resources :products, only: [:index, :show] do 
    member do 
      post :add_to_cart
    end
  end

  resource :profile
  resources :offers, only: :create do 
    member do
      patch 'offer', as: 'vote'
    end
  end

  namespace :admin do
    root 'admin#root'
    resources :users, except: [:new, :create]
    resources :products, except: :show
    resources :offers, except: :show
  end

  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'
  
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	belongs_to :user
	has_many :cart_items, dependent: :destroy
	has_many :products, :through => :cart_items

	scope :active, -> { where(status: true) }
	
	def is_empty?
		cart_items.empty?
	end

	def add_product(pr)
		item = CartItem.find_by(product_id: pr.id, cart_id: id)
		if item
			item.quantity += 1
			item.save!
		else
			item = CartItem.create(product_id: pr.id, cart_id: id, price: pr.price)
		end
		item.save!
		item
	end

	def delete_product(pr)
		item = CartItem.find_by(product_id: pr.id, cart_id: id)
		if item 
			if item.quantity > 1
				item.quantity -= 1
				item.save!
			else
				item.destroy
			end
			item
		else
			fail "RecordNotFound"
		end
	end

	def total_items
		cart_items.inject(0) { |count, t| count + t.quantity }
	end

	def total_sum
		cart_items.inject(0) { |sum, t| sum + t.total_price }
	end

	def check_out(adress)
	    item_all = CartItem.where(cart_id: id)
	    order = Order.new(adress: adress, user: user)
	    item_all.each do |item|
	    	order_item = OrderItem.create(product_id: item.product_id, price: item.price, quantity: item.quantity)
	    	order.order_items << order_item
		end
		order.save!
		self.status = false 
		save!
		order
	end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	
	before_action :set_cart

	def show
		@cart_items = @cart.cart_items
		#render json: @cart_items.as_json  
	end

	private

	def set_cart
		@cart = current_cart
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/check_out.html.erb
<h3>Chek out</h3>
<% @cart_items.each do |ci| %> 
  <ul>
	<li><%= ci.product.title %><%= " x#{ci.quantity}" %> </li>
	<li><%= ci.product.description %></li>
	<li><%= ci.product.price %></li>
  </ul>
<% end %>

<%= form_for user_cart_path do |f| %>
  <%= f.label 'address:' %><br>
  <%= f.text_field :adress %><br>
  <%= f.submit "Check_out" %>
<% end %>

app/views/carts/show.html.slim
.table-responsive
	table.table
		thead
			tr
				th #
				th style="width: 1px;" Image
				th Title
				th Price
				th Count
				th Sum
		tbody
			- @cart_items.each_with_index do |item, i|
				tr
					td = i + 1
					td
						a href="#{product_path(item.product_id)}"
							img src="assets/try.jpg" style="max-width: 50px; max-height: 50px;"
					td 
						p 
							strong = item.product.title
						p = truncate(item.product.description, length: 50)
					td = "#{item.price}$"
					td = item.quantity
					td = "#{item.total_price}$"
	
		tfoot
			tr
				td 
				td 
				td Total price:
				td
				td
				td = "#{@cart_items.reduce(0) { |sum, a| sum + a.total_price } }$"