config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#home'

  resource :cart, only: [:show] 
  resources :orders 

  resources :products, only: [:index, :show] do 
    member do 
      post :add_to_cart
    end
  end

  resource :profile
  resources :offers, only: :create do 
    member do
      patch 'offer', as: 'vote'
    end
  end

  namespace :admin do
    root 'admin#root'
    resources :users, except: [:new, :create]
    resources :products, except: :show
    resources :offers, except: :show
  end

  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'
  
end

app/models/offer.rb
class Offer < ActiveRecord::Base
	has_many :vote_options
	validates :topic, presence: true

	scope :visible, -> { where(visible: true) }
	scope :unvisible, -> { where(visible: false) }

	def normalized_votes_for(option)
    	vote_summary == 0 ? 0 : ((option.votes_count.to_f / vote_summary) * 100).round(1)
  	end

	def vote_summary
		vote_options.inject(0) { |sum, opt| sum + opt.votes_count }
	end

end

app/controllers/admin/offers_controller.rb
class Admin::OffersController < Admin::AdminController
	before_action :find_offer, only: [:edit, :update, :destroy]
	
	def index
		@offers = Offer.all
	end

	def new
		@offer = Offer.new
	end

	def create
		@offer = Offer.new(params_offer)
		@offer.vote_options = create_options
		if @offer.save
			redirect_to admin_offers_path, notice: "Offer was created"
		else
			render :new		
		end
	end

	def edit
	end

	def update
		if @offer.update_attributes(params_offer)
			flash[:success] = "Updated"
			redirect_to admin_offers_path, notice: "Offer was updated" 
		else
			render :edit
		end
	end

	def destroy
		@offer.destroy
		redirect_to admin_offers_path
	end

	private

	def find_offer
		@offer = Offer.find(params[:id])
	end

	def params_offer
		params.require(:offer).permit(:topic, :image, :visible)
	end

	def create_options
		return VoteOption.create(title: "Да"), VoteOption.create(title: "Нет")
	end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
	before_action { session[:vote_offers] ||= {} }
#	def index 
#		@offers = Offer.visible
#	end

	def offer
		if params[:offer] && params[:vote_option][:id]
			@offer = Offer.find(params[:offer][:id])
			@offers_option = @offer.vote_options.find(params[:vote_option][:id])
			if @offer && @offers_option && !session[:vote_offers][params[:vote_option][:id]]
				inc_vote_count
				add_cookies
				render 'offers/update'
			end
		end 
	end

	def create 
		@offer = Offer.new(params_offer)
		@offer.vote_options = craete_options
		if offer.save
			redirect_to offers_path, notice: "Offer was created"
		else
			render :new
		end 
	end

	private

	def params_offer
		params.require(:offer).permit(:topic)
	end

	def create_options
		return VoteOption.create(title: "Да"), VoteOption.create(title: "Нет")
	end

	def inc_vote_count
		@offers_option.votes_count += 1
		@offers_option.save!
	end

	def add_cookies
		session[:vote_offers][params[:offer][:id]] = {vote_options_id: params[:vote_option][:id]}
	end

end

app/helpers/admin/offers_helper.rb
module Admin::OffersHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.slim
= form_tag vote_offer_path(offer), method: :patch, remote: true, class: "offer#{offer.id}" do 
	= hidden_field_tag 'offer[id]', offer.id

	- if session[:vote_offers] and session[:vote_offers][offer.id.to_s]
		- offer.vote_options.each do |option|
			- value = offer.normalized_votes_for option
			label = "#{option.title}"
			.progress
				.progress-bar@progressbar  aria-valuenow="#{value}" aria-valuemin="0" aria-valuemax="100" style="width: #{value}%;"
					= value.to_s + "%"
	- else
		- offer.vote_options.each do |option|
			.radio
				label
					input id="optionsRadios" type="radio" name="vote_option[id]" value="#{option.id}"
						= option.title
		= submit_tag "Vote!", class: "btn btn-primary"

app/views/offers/_offer.html.slim
.panel-heading
	h3.panel-title = offer.topic
.panel-body
	= render 'offers/form', offer: offer

app/views/offers/update.js.erb
$('.<%= "offer#{@offer.id}" %>').replaceWith('<%= j render "offers/form", offer: @offer %>')