config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#home'

  resource :cart, only: [:show] 
  resources :orders 

  resources :products, only: [:index, :show] do 
    member do 
      post :add_to_cart
    end
  end

  resource :profile
  resources :offers, only: :create do 
    member do
      patch 'offer', as: 'vote'
    end
  end

  namespace :admin do
    root 'admin#root'
    resources :users, except: [:new, :create]
    resources :products, except: :show
    resources :offers, except: :show
  end

  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'
  
end

app/models/product.rb
class Product < ActiveRecord::Base

	has_many :images, as: :imageable

	validates :price, allow_blank: true, numericality: { greater_than_or_equal_to: 0.01, message: 'Некорректная цена' }
	validates :title, uniqueness: true

	scope :top10, -> { top.limit(10) }

	def self.top
		group(:product_id).order('sum(order_items.quantity) DESC').joins(:order_items)
	end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController

	before_action :set_product, except: [:create, :new, :index]

	def index
		@products = Product.all
	end

	def edit
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to admin_products_path, notice: "Product is created"
		else
			render :new
		end
	end

	def update
		if @product.update(product_params)
			redirect_to admin_products_path, notice: "Product is updated"
		else 
			render :edit
		end
	end

	def destroy
		@product.destroy
		redirect_to admin_products_path, notice: "Product is deleted"
	end		

private 
	
	def product_params
		params.require(:product).permit(:title, :description, :price)
	end

	def set_product
		@product = Product.find(params[:id])
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :set_product, except: [:index, :new, :create]

	def index
		@products = Product.all
		respond_to do |format|
    		format.html
    		format.json { render json: @products.as_json(only: [:id, :title, :description, :price], include: [:orders]) }
  		end
	end

	def new 
		@product = Product.new
	end	

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to @product
		else
			render action: 'new'
		end
	end

	def edit
	end

	def show
		respond_to do |f|
			f.html
			f.json { render json: @product.as_json(include: [:orders, :order_items])}
		end
	end

	def update
		if @product.update(product_params)
			redirect_to @product
		else
			render :edit
		end
	end

	def destroy
		@product.destroy
		redirect_to :products
	end

	def add_to_cart
		current_cart.add_product(@product)
		redirect_back_or products_path
	end

	def top10
		@products = Product.top10
		render json: @products.as_json(include: :order_items)
	end

	private

	def product_params
		params.require(:product).permit(:title, :description, :price)  #в чем разница, если писать без require?
		#Объяснить метод permit
	end

	def set_product 
		@product = Product.find(params[:id])
	end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_error_messages.html.erb
<% if @product.errors.any? %>
	<p> Errors: </p>
	<ul>
		<% @product.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

app/views/admin/products/edit.html.erb
<%= form_for @product, url: admin_product_path(@product) do |f| %>
<%= render 'error_messages' %>
<%= @product.errors.each { |e| puts e } %>
<p>
	<%= f.label :title %>
	<%= f.text_field :title %>
</p>
<p>
	<%= f.label :description %>
	<%= f.text_field :description %>
</p>
<p>
	<%= f.label :price %>
	<%= f.text_field :price %>
</p>
<p><%= f.submit "Update" %></p>
<% end %>	

app/views/admin/products/index.html.erb
<ul>
<% @products.each do |prod| %>
	<li>
	<%= prod.title %> 
	<%= link_to "Edit", edit_admin_product_path(prod) %> 
	<%= link_to "Delete", admin_product_path(prod), method: :delete %>
	</li>
<% end %>
</ul>
<p><%= link_to "Create a new Product", new_admin_product_path %></p>

app/views/admin/products/new.html.erb
<%= form_for @product, url: admin_products_path(@product), remote: true do |f| %>
<%= render 'error_messages' %>
<p>
	<%= f.label :title %>
	<%= f.text_field :title %>
</p>
<p>
	<%= f.label :description %>
	<%= f.text_field :description %>
</p>
<p>
	<%= f.label :price %>
	<%= f.text_field :price %>
</p>
<p><%= f.submit "Create" %></p>
<% end %>